name: campusnet
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  icons_plus: ^5.0.0
  riverpod: ^3.2.1
  dio: ^5.9.1
  supabase: ^2.10.2
  supabase_flutter: ^2.12.0
  http: ^1.6.0
  shared_preferences: ^2.5.4
  shared_preferences_windows: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/LoginPageImage.jpg
    - assets/images/LoginPageImage2.jpg
    - assets/images/LoginPageImage3.jpg
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
